feature: simulate scene until a specific object emits a signal
MikeSchulze/gdUnit3 pull request #148
Opened 2021-09-13 06:56 UTC by derkork

Currently, the runner only allows to simulate until the scene object itself emits a signal. Very often however we have objects in the scene that we try to simulate and the scene itself is just a test harness. With this new function the scene runner can now simulate the scene until any object that is given to the function will emit a specific signal.

2021-09-13 16:06 UTC, MikeSchulze commented
Thank you for improving GdUnit3 with this feature request.
Please also add a test coverage at `res://addons/gdUnit3/test/core/GdUnitSceneRunnerTest.gd`.
This will also give me a better understanding.

2021-09-14 05:03 UTC, MikeSchulze commented
Ok I now understand the point of how to use it,
I have a Demo3DRoom test example where a scene is running until a door is closed.
Currently the door signal is delegated to the main scene, with this new function I can run the scene by testing the door signal directly without having to delegate the signal.

I will extend the demo with the new runner function.
Best thanks.

2021-09-14 05:06 UTC, MikeSchulze requested changes
Looks good, please fix the small thinks i commented ;)
Than i will merge it.

2021-09-14 05:06 UTC, MikeSchulze commented on addons/gdUnit3/src/core/GdUnitSceneRunner.gd
> +func simulate_until_object_signal(source:Object, signal_name: String, arg0 = null, arg1 = null, arg2 = null, arg3 = null, arg4 = null, arg5 = null) -> GdUnitSceneRunner:
```suggestion
func simulate_until_object_signal(source :Object, signal_name: String, arg0 = null, arg1 = null, arg2 = null, arg3 = null, arg4 = null, arg5 = null) -> GdUnitSceneRunner:
```

2021-09-14 05:06 UTC, MikeSchulze commented on addons/gdUnit3/src/core/GdUnitSceneRunner.gd
> +
please remove the empty line

2021-09-14 05:26 UTC, derkork commented
Hi, sorry for the slow reply, I had been busy with other things yesterday. Glad that this is useful. I have added the requested formatting.

2021-09-14 08:59 UTC, MikeSchulze approved these changes

2021-09-14 08:59 UTC, merged